apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
    selector:
     app: wisecow
    ports:
    - protocol: TCP
      port: 80        # The port that the service will expose internally
      targetPort: 4499 # The port on the pod that the service should forward to
        # Optional: The port on each node that will be exposed (Kubernetes will choose a port if not specified)
    type: NodePort












